# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-25 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0002_auto_20200325_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='durasi_pengobatan',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pasien',
            name='jenis_pengobatan',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='nama_dokter',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='nama_pasien',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='umur',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='update_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasien',
            name='waktu_berakhir',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AddField(
            model_name='pasien',
            name='waktu_mulai',
            field=models.CharField(blank=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
    ]
