# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0003_auto_20200325_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
