# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-25 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0005_auto_20200326_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasien',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
