# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0007_auto_20200331_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(max_length=191)),
                ('no_ktp', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('l', 'L'), ('p', 'P')], default='l', max_length=1)),
                ('tempat_tgl_lahir', models.CharField(blank=True, max_length=191)),
                ('Status', models.CharField(max_length=191)),
                ('gol_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2)),
                ('no_telp', models.CharField(max_length=12)),
                ('alamat', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='NoAntrian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
