# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0010_auto_20200402_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('l', 'Laki-laki'), ('p', 'Perempuan')], default='l', max_length=10),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_pengobatan',
            field=models.CharField(max_length=191),
        ),
    ]
