# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0012_auto_20200513_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapasien',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapasien',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noantrian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noantrian',
            name='data_pasien',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='antrian.DataPasien'),
        ),
        migrations.AddField(
            model_name='noantrian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
