# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0013_auto_20200513_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='noantrian',
            name='status',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
