# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0014_noantrian_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noantrian',
            name='pemanggil',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
