# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0015_noantrian_pemanggil'),
    ]

    operations = [
        migrations.AddField(
            model_name='noantrian',
            name='jenis_pengobatan',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
