# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0016_noantrian_jenis_pengobatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='no_antrian',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='antrian.NoAntrian'),
        ),
    ]
