# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('antrian', '0019_auto_20200522_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noantrian',
            name='data_pasien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='antrian.DataPasien'),
        ),
        migrations.AlterField(
            model_name='noantrian',
            name='pasien',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='antrian.Pasien'),
        ),
    ]
